package api

import (
	"context"
	"encoding/json"
	"net/url"
	"time"

	"github.com/trypando/pando/internal/secret"
)

// Category names an adapter category.
type Category string

const (
	CategoryIdentity Category = "identity"
	CategoryRouting  Category = "routing"
	CategoryBuilder  Category = "builder"
	CategoryRuntime  Category = "runtime"
	CategorySecrets  Category = "secrets"
	CategoryServices Category = "services"
	CategoryNotify   Category = "notify"

	// CategoryBackup is the eighth (R-252), added in phase 9. It reverses a
	// decision recorded in design 03 §8.1 through phase 8; that section now
	// carries the reversal and the reasoning, rather than the change being
	// visible only here.
	CategoryBackup Category = "backup"

	// CategoryScanner is the ninth (R-317), added with the security score.
	// Pando translates a scanner's findings into a number and a policy
	// decision; it does not implement one. See design 09.
	CategoryScanner Category = "scanner"

	// CategoryAI is the tenth (R-258), and the first that is optional in the
	// strong sense: an install with none configured is not degraded, because
	// everything the auction produces is produced either way (R-106).
	// Design 10 has the argument for why it is a category at all.
	CategoryAI Category = "ai"

	// CategorySource is the eleventh (R-091): a connection to a place
	// repositories live, which apps from private repositories are cloned
	// with. See source.go.
	CategorySource Category = "source"

	// CategoryImageRegistry is the twelfth (R-252, issue #153): the registry
	// Pando pushes a build to when the runtime pulls rather than imports. It
	// was install configuration until the providers' differences — which
	// create a repository on push, which mint a password — turned out to be
	// the planner's questions. See imageregistry.go.
	CategoryImageRegistry Category = "image_registry"
)

// Adapter is implemented by every adapter in every category.
type Adapter interface {
	Kind() string
	Category() Category
	Configure(ctx context.Context, raw json.RawMessage) error

	// HealthCheck lets the planner refuse to plan against an unhealthy adapter
	// and return ADAPTER_UNAVAILABLE, rather than failing mid-deploy (R-254).
	HealthCheck(ctx context.Context) error
}

// IdentityAdapter authenticates. It does not authorize (R-044).
//
// Stateless between calls. A redirect sign-in spans two requests, and what an
// adapter must remember from the first to check the second — a PKCE verifier
// and nonce, a SAML request ID — goes back to core as Redirect.Flow and returns
// in Credential.Flow. Core stores it, binds it to the browser that started the
// flow, and consumes it once; an adapter never touches state (R-027).
type IdentityAdapter interface {
	Adapter

	// Begin returns where to send the user, or nil for adapters that
	// authenticate inline, such as local username and password.
	Begin(ctx context.Context, req BeginRequest) (*Redirect, error)

	// Authenticate resolves an inbound callback or credential to a subject.
	Authenticate(ctx context.Context, c Credential) (Subject, error)

	// ServiceMetadata is what the provider is given to trust Pando — SAML
	// service provider metadata. Nil for adapters that have none.
	ServiceMetadata(ctx context.Context, e Endpoints) (*Metadata, error)

	// SessionPolicy is how R-047 is honored mechanically: each adapter declares
	// its own lifetime and revocation mode, so the console can show the real
	// window per adapter instead of implying a global guarantee.
	SessionPolicy() SessionPolicy

	// SupportsPush reports whether the adapter's provider can push changes
	// (SCIM or webhook), which is what makes immediate revocation possible
	// (R-048). Whether an installation has turned that on is core's to know:
	// a provider that can push but has no SCIM token pushes nothing, and core
	// reports its revocation as the session lifetime (R-050).
	SupportsPush() bool
}

// Endpoints are where Pando receives a provider's responses.
//
// Core computes them from the install's external URL and hands them over. An
// adapter never works out its own address: behind a TLS-terminating proxy it
// would get it wrong, and a redirect URI must match the registered one to the
// character.
type Endpoints struct {
	// CallbackURL is the OIDC redirect_uri, or the SAML Assertion Consumer
	// Service URL.
	CallbackURL string

	// EntityID is the SAML service provider's entity ID, which is also the URL
	// its metadata is published at. Unused by OIDC.
	EntityID string
}

// BeginRequest starts a redirect sign-in.
type BeginRequest struct {
	Endpoints

	// State is opaque, generated by core and bound to the browser. The adapter
	// sends it to the provider (OIDC state, SAML RelayState) and it comes back
	// on the callback, which is how core finds the flow.
	State string
}

// Redirect sends the user to an external identity provider.
type Redirect struct {
	URL string

	// Flow is the adapter's own data for this sign-in, returned to it in
	// Credential.Flow. Opaque to core.
	Flow []byte
}

// Metadata is a document a provider is given about Pando.
type Metadata struct {
	ContentType string
	Body        []byte
}

// Credential is inbound authentication material.
type Credential struct {
	// Username and Password for inline adapters.
	Username string
	Password secret.Value

	// For redirect adapters: the parameters the provider sent back, as query
	// or form values; the Flow its Begin returned; and the endpoints the flow
	// used. Flow is nil for a sign-in the provider started (SAML
	// IdP-initiated), which an adapter refuses unless configured to allow it.
	Callback url.Values
	Flow     []byte
	Endpoints
}

// Subject is who the adapter says this is.
//
// It carries no roles, no verbs, and no permissions. Group *names* cross this
// boundary; what a group can *do* is Pando's (R-078).
type Subject struct {
	// ExternalID is stable within this adapter. It is not what the rest of
	// Pando uses — users.id is (R-054).
	ExternalID  string
	Email       string
	DisplayName string
	Groups      []string

	// Username is the name the provider knows the person by, when it says.
	Username string

	// EmailVerified is the provider vouching that the email belongs to this
	// person. Linking by email is only ever done on it (O-1): an email a person
	// can set for themselves is a way into somebody else's account.
	EmailVerified bool

	// Attributes are the claims or attributes the provider sent, for an
	// administrator's test sign-in to show. Nothing reads them to decide
	// anything.
	Attributes map[string][]string

	// OneTimeID is an identifier the provider promises is used once — a SAML
	// assertion ID — valid until OneTimeUntil. Core refuses a second use,
	// which is what stops a captured response from being replayed.
	OneTimeID    string
	OneTimeUntil time.Time
}

// RevocationMode describes how quickly an adapter can revoke.
type RevocationMode string

const (
	// RevocationPush means the provider notifies Pando, so revocation is
	// immediate (R-048).
	RevocationPush RevocationMode = "push"
	// RevocationRefresh means Pando learns at the next refresh.
	RevocationRefresh RevocationMode = "refresh"
	// RevocationExpiryOnly means access ends when the session expires, and
	// nothing sooner. The console must say so rather than implying otherwise.
	RevocationExpiryOnly RevocationMode = "expiry_only"
)

// SessionPolicy is an adapter's own session behavior (R-047).
type SessionPolicy struct {
	MaxLifetime     time.Duration
	RevocationMode  RevocationMode
	RefreshInterval time.Duration
}
