// Generated by cmd/gen-api-types. Do not edit.
//
// These are the Go types the API serializes, mechanically translated. R-261
// makes the API authoritative, and design 08 §1.2 says these are generated for
// that reason: a hand-written type is a second opinion about what the server
// returns, and the two drift the first time a field is added.
//
// Regenerate with: npm run types

export interface App {
  id: string;
  name: string;
  slug: string;
  owner_user_id: string;
  state: string;
  desired_state: string;
  pinned_spec_id?: string;
  source: Source;
  created_at: string;
  updated_at: string;
  deleted_at?: string;
  routing?: Routing;
  address?: string;
  security_score?: number;
  security_verdict?: string;
  security_scanning?: boolean;
  icon_updated_at?: string;
  favorite?: boolean;
  section_id?: string;
  detection?: DetectionSummary;
}

export interface Section {
  id: string;
  name: string;
  created_at: string;
}

export interface Revision {
  id: string;
  app_id: string;
  revision: number;
  origin: string;
  body?: AppSpec;
  created_by: string;
  created_at: string;
  ever_pinned: boolean;
}

export interface Deployment {
  id: string;
  app_id: string;
  spec_id: string;
  trigger: string;
  status: string;
  result_state?: string;
  error_code?: string;
  error_detail?: string;
  started_at: string;
  finished_at?: string;
  created_by: string;
  spec_revision?: number;
  requested_by_name?: string;
  approvals_required?: number;
  approval_expires_at?: string;
  approval_reasons?: (ApprovalReason[] | null);
  approvals?: (ApprovalDecision[] | null);
  can_decide?: boolean;
}

export interface AwaitingApproval {
  id: string;
  app_id: string;
  spec_id: string;
  trigger: string;
  status: string;
  result_state?: string;
  error_code?: string;
  error_detail?: string;
  started_at: string;
  finished_at?: string;
  created_by: string;
  spec_revision?: number;
  requested_by_name?: string;
  approvals_required?: number;
  approval_expires_at?: string;
  approval_reasons?: (ApprovalReason[] | null);
  approvals?: (ApprovalDecision[] | null);
  can_decide?: boolean;
  app_name: string;
  app_slug: string;
}

export interface Detection {
  app_id: string;
  status: string;
  body: unknown;
  answers: (Record<string, string> | null);
  commit?: string;
  started_at: string;
  updated_at: string;
}

export interface GrantRow {
  id: string;
  app_id: string;
  plane: string;
  principal_kind: string;
  principal_id?: string;
  role_id?: string;
  principal_name?: string;
  role_name?: string;
  passcode?: boolean;
}

export interface User {
  id: string;
  adapter_id: string;
  external_id: string;
  email?: string;
  display_name?: string;
  status: string;
  must_change_password: boolean;
  alias_of?: string;
  created_at: string;
}

export interface Proposal {
  status: string;
  winning_bid: Candidate;
  runners_up: (Candidate[] | null);
  questions: (Question[] | null);
  draft_spec: AppSpec;
  blocked?: Error;
  trial_log?: string;
  commit?: string;
  trial?: TrialObservation;
  screening?: Outcome;
  conversation?: (Turn[] | null);
}

export interface Candidate {
  detector: string;
  strategy: string;
  confidence: number;
  evidence?: (string[] | null);
  questions?: (Question[] | null);
  draft?: Draft;
  spec?: AppSpec;
}

export interface Question {
  key: string;
  prompt: string;
  why: string;
  kind: string;
  options?: (string[] | null);
  deferred?: boolean;
  suggested?: Suggestion;
}

export interface AppSpec {
  schema_version: number;
  app_id: string;
  revision: number;
  created_at: string;
  created_by: string;
  origin: string;
  source: Source;
  build: Build;
  workloads: (Workload[] | null);
  volumes: (Volume[] | null);
  slots: (Slot[] | null);
  routing: Routing;
  runtime: RuntimeRef;
  deploy: Deploy;
  health: Health;
  resources: Resources;
  egress: Egress;
  retention: Retention;
  warnings?: (Warning[] | null);
}

export interface Error {
  code: string;
  message: string;
  remedy?: string;
  details?: (Record<string, unknown> | null);
  request_id?: string;
}

export interface Document {
  api: API;
  cli: (Command[] | null);
  mcp: (ToolDoc[] | null);
  errors: (CodeDoc[] | null);
  events: (Def[] | null);
  connect: Connect;
  install: Install;
}

export interface Token {
  id: string;
  kind: string;
  name: string;
  owner_user_id?: string;
  expires_at?: string;
  last_used_at?: string;
  revoked_at?: string;
}

export interface Report {
  standing: Standing;
  scan?: Scan;
  counts: Counts;
  worst?: (Finding[] | null);
  scanner?: string;
  scanning_since?: string;
  ignoring_unfixable: boolean;
}

export interface PolicyDocument {
  source_allowlist?: (string[] | null);
  disabled_verbs?: (string[] | null);
  agent_disabled_verbs?: (string[] | null);
  allow_anonymous_grants?: boolean;
  public_sharing?: string;
  min_build_isolation?: number;
  min_runtime_isolation?: number;
  egress_mode?: string;
  egress_list?: (string[] | null);
  egress_block_private?: boolean;
  egress_loosening?: string;
  egress_allowlist?: (string[] | null);
  deploy_approval_required?: boolean;
  deploy_approval_apps?: (string[] | null);
  deploy_approval_count?: number;
  deploy_approval_expiry_hours?: number;
  require_backup_before_destroy?: boolean;
  max_token_lifetime_days?: number;
  max_log_disk_bytes?: number;
  audit_retention_months?: number;
  audit_archive?: string;
  audit_archive_destination?: string;
  disable_ai_screening?: boolean;
  disable_anonymous_use_audit?: boolean;
  min_security_score?: number;
  insecure_action?: string;
  insecure_grace_hours?: number;
  ignore_unfixable_findings?: boolean;
  disable_password_sign_in?: boolean;
  disable_jit_provisioning?: boolean;
  disable_update_check?: boolean;
  allow_private_webhooks?: boolean;
  update_channel?: string;
  upgrade_in_place?: boolean;
  auto_upgrade_patches?: boolean;
  maintenance_window?: string;
}

export interface BackupAttempt {
  app_id: string;
  app_name?: string;
  attempted_at: string;
  outcome: string;
  backup_id?: string;
  message?: string;
  remedy?: string;
}

export interface ProviderView {
  id: string;
  kind: string;
  name: string;
  config: unknown;
  enabled: boolean;
  jit_provisioning: boolean;
  link_by_email: boolean;
  scim_enabled: boolean;
  scim_token_created_at?: string;
  scim_identity_attribute: string;
  created_at: string;
  updated_at: string;
  credentials: (string[] | null);
  callback_url?: string;
  entity_id?: string;
  metadata_url?: string;
  scim_base_url?: string;
  revocation?: Revocation;
  problem?: string;
}

export interface SignInOptions {
  password_sign_in: boolean;
  providers: (PublicProvider[] | null);
}

export interface TestReport {
  ok: boolean;
  error?: Problem;
  subject?: SubjectView;
  attributes?: (Record<string, (string[] | null)> | null);
  outcome?: SignInOutcome;
}

export interface Problem {
  code: string;
  message: string;
  remedy?: string;
}

export interface Identity {
  adapter_id: string;
  adapter_name: string;
  adapter_kind: string;
  external_id: string;
  user_id: string;
  origin: boolean;
  scim: boolean;
  last_sign_in_at?: string;
  created_by: string;
  created_at: string;
}

export interface Group {
  id: string;
  name: string;
  source?: string;
  source_name?: string;
  members?: (string[] | null);
  linked_from?: (string[] | null);
  links_to?: (string[] | null);
  created_at: string;
}

export interface Status {
  current: string;
  development: boolean;
  enabled: boolean;
  channel: string;
  checked_at?: string;
  error?: string;
  latest?: string;
  available: boolean;
  releases: (Release[] | null);
  security: boolean;
  breaking: boolean;
  upgrade?: Upgrade;
}

export interface Plan {
  current: string;
  target: string;
  possible: boolean;
  reasons: (string[] | null);
  image?: string;
  tag?: string;
  breaking: (Release[] | null);
  note: string;
}

export interface Attempt {
  id: string;
  from: string;
  to: string;
  image: string;
  tag?: string;
  started_at: string;
  started_by: string;
  automatic: boolean;
  backup_id?: string;
  skip_backup: boolean;
  state: string;
  finished_at?: string;
  reason?: string;
  logs?: string;
  snapshot_at?: string;
  snapshot_gone: boolean;
  recorded: boolean;
}

export interface Source {
  type: string;
  url?: string;
  ref?: string;
  commit?: string;
  subdir?: string;
  image?: string;
  digest?: string;
  upload_id?: string;
  credential_ref?: string;
}

export interface Routing {
  adapter_ref: string;
  mode: string;
  mode_source: string;
  hostname?: string;
  path_prefix?: string;
  port?: number;
}

export interface DetectionSummary {
  status: string;
  stage?: string;
  started_at: string;
  updated_at: string;
}

export interface ApprovalReason {
  reason: string;
  message: string;
}

export interface ApprovalDecision {
  principal_id: string;
  principal_name: string;
  decision: string;
  comment?: string;
  decided_at: string;
}

export interface TrialObservation {
  ran?: boolean;
  started?: boolean;
  crashed?: boolean;
  observed_ports?: (number[] | null);
  observed_writes?: (string[] | null);
}

export interface Outcome {
  ran: boolean;
  skipped?: string;
  skip_code?: string;
  function?: string;
  why?: string;
  adapter_ref?: string;
  model?: string;
  files_read?: (string[] | null);
  applied?: (Applied[] | null);
  refused?: (Refused[] | null);
  answers?: (Record<string, string> | null);
  notes?: (string[] | null);
  duration_ms?: number;
}

export interface Turn {
  from: string;
  text: string;
  at: string;
  changes?: (string[] | null);
  refused?: (string[] | null);
  files_read?: (string[] | null);
}

export interface Draft {
  workloads?: (Workload[] | null);
  volumes?: (Volume[] | null);
  slots?: (Slot[] | null);
  build: Build;
  health?: Health;
  warnings?: (Warning[] | null);
}

export interface Suggestion {
  value: string;
  reason?: string;
  evidence?: (string[] | null);
}

export interface Build {
  strategy: string;
  adapter_ref: string;
  dockerfile?: string;
  context?: string;
  target?: string;
  compose_file?: string;
  static_dir?: string;
  generated_files?: (Record<string, string> | null);
  args?: (KV[] | null);
  isolation_floor: number;
  timeout_seconds: number;
  egress_mode: string;
  egress_allow?: (string[] | null);
}

export interface Workload {
  name: string;
  image?: string;
  command?: (string[] | null);
  entrypoint?: (string[] | null);
  working_dir?: string;
  env?: (EnvEntry[] | null);
  ports?: (Port[] | null);
  mounts?: (Mount[] | null);
  files?: (File[] | null);
  depends_on?: (string[] | null);
  healthcheck?: Healthcheck;
  exposed: boolean;
  primary: boolean;
  resources?: ResourceLimits;
  build?: WorkloadBuild;
}

export interface Volume {
  id: string;
  name: string;
  declared: string;
  size_hint_bytes?: number;
}

export interface Slot {
  key: string;
  type: string;
  required: boolean;
  evidence?: (string[] | null);
  resolution?: Resolution;
}

export interface RuntimeRef {
  adapter_ref: string;
  isolation_floor: number;
}

export interface Deploy {
  strategy: string;
  auto_deploy: AutoDeploy;
  auto_rollback: boolean;
  require_approval?: boolean;
}

export interface Health {
  source: string;
  path?: string;
  port?: number;
  interval_seconds: number;
  timeout_seconds: number;
  retries: number;
}

export interface Resources {
  cpu_millis: number;
  memory_bytes: number;
  disk_bytes: number;
  overridden: boolean;
}

export interface Egress {
  mode: string;
  list?: (string[] | null);
  add?: (string[] | null);
  remove?: (string[] | null);
  block_private?: boolean;
  allowlist?: (string[] | null);
}

export interface Retention {
  log_bytes: number;
  backup_daily_count: number;
  spec_revisions: number;
}

export interface Warning {
  code: string;
  message: string;
  dismissed: boolean;
  dismissed_by?: string;
}

export interface API {
  base_path: string;
  auth: (Auth[] | null);
  routes: (Route[] | null);
}

export interface Command {
  name: string;
  use: string;
  summary: string;
  details?: string;
  flags?: (Flag[] | null);
  children?: (Command[] | null);
}

export interface ToolDoc {
  name: string;
  description: string;
  schema: (Record<string, unknown> | null);
}

export interface CodeDoc {
  code: string;
  status: number;
  meaning: string;
}

export interface Def {
  name: string;
  scope: string;
  source: string;
  summary: string;
  fields: (Field[] | null);
}

export interface Connect {
  server_env: string;
  token_env: string;
  login_cmd: string;
  mcp_cmd: string;
}

export interface Install {
  repo: string;
  module: string;
  homebrew: string;
  packages: (string[] | null);
  archive: string;
  package: string;
  download: string;
  platforms: (string[] | null);
  in_container: string;
}

export interface Standing {
  verdict: string;
  score?: number;
  threshold: number;
  scanned?: string;
  stop_at?: string;
}

export interface Scan {
  id: string;
  app_id: string;
  spec_id?: string;
  commit?: string;
  scanner_ref: string;
  scanner?: string;
  score?: number;
  score_fixable?: number;
  findings: (Finding[] | null);
  error?: string;
  ran_at: string;
  reused_from?: string;
}

export interface Counts {
  critical: number;
  high: number;
  medium: number;
  low: number;
  unknown: number;
}

export interface Finding {
  id: string;
  severity: string;
  title: string;
  target: string;
  fix?: string;
}

export interface Revocation {
  max_lifetime_seconds: number;
  mode: string;
  window_seconds: number;
}

export interface PublicProvider {
  id: string;
  name: string;
  kind: string;
}

export interface SubjectView {
  external_id: string;
  username?: string;
  email?: string;
  email_verified: boolean;
  display_name?: string;
  groups: (string[] | null);
}

export interface SignInOutcome {
  kind: string;
  user_id?: string;
  username?: string;
  display_name?: string;
  message?: string;
  remedy?: string;
  groups?: (string[] | null);
  groups_from: string;
}

export interface Release {
  version: string;
  prerelease: boolean;
  published_at: string;
  url: string;
  notes: string;
  security: boolean;
  breaking: boolean;
}

export interface Upgrade {
  version: string;
  image?: string;
  command: string;
  instructions: string;
}

export interface Applied {
  amendment: Amendment;
  summary: string;
}

export interface Refused {
  amendment: Amendment;
  reason: string;
}

export interface KV {
  key: string;
  value: string;
}

export interface EnvEntry {
  key: string;
  value?: string;
  slot_ref?: string;
  secret_ref?: string;
  source?: string;
}

export interface Port {
  number: number;
  protocol: string;
  source: string;
}

export interface Mount {
  volume_id: string;
  path: string;
  read_only: boolean;
}

export interface File {
  path: string;
  content: string;
  mode?: number;
}

export interface Healthcheck {
  command?: (string[] | null);
  path?: string;
  port?: number;
  interval_seconds?: number;
  timeout_seconds?: number;
  retries?: number;
}

export interface ResourceLimits {
  cpu_millis?: number;
  memory_bytes?: number;
}

export interface WorkloadBuild {
  context?: string;
  dockerfile?: string;
  target?: string;
  args?: (KV[] | null);
}

export interface Resolution {
  mode: string;
  service_ref?: string;
  target?: string;
  secret_ref?: string;
}

export interface AutoDeploy {
  enabled: boolean;
  trigger?: string;
  branch?: string;
}

export interface Auth {
  name: string;
  how: string;
  description: string;
}

export interface Route {
  method: string;
  path: string;
  group: string;
  summary: string;
  verb?: string;
}

export interface Flag {
  name: string;
  shorthand?: string;
  description: string;
  default?: string;
}

export interface Field {
  name: string;
  description: string;
}

export interface Amendment {
  kind: string;
  workload?: string;
  key?: string;
  value?: string;
  command?: (string[] | null);
  path?: string;
  port?: number;
  slot_type?: string;
  required?: boolean;
  reason: string;
  evidence: (string[] | null);
}

