package main

import (
	"encoding/json"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/trypando/pando/internal/core/policy"
	"github.com/trypando/pando/internal/reference"
)

// render emits the declarations for one type, the way generate() does for the
// exported list.
func render(t *testing.T, v any) string {
	t.Helper()
	g := &generator{done: map[reflect.Type]bool{}}
	g.enqueue(reflect.TypeOf(v))

	for len(g.queue) > 0 {
		next := g.queue[0]
		g.queue = g.queue[1:]
		require.NoError(t, g.writeInterface(next))
	}
	return g.buf.String()
}

func tsTypeOf(t *testing.T, v any) string {
	t.Helper()
	g := &generator{done: map[reflect.Type]bool{}}
	got, err := g.tsType(reflect.TypeOf(v))
	require.NoError(t, err)
	return got
}

// R-261 makes the API authoritative, and design 08 §1.2 says these are
// generated: a hand-written type is a second opinion about what the server
// returns, and the two drift the first time a field is added.
func TestR261_TheRealAPITypesGenerateWithoutAGap(t *testing.T) {
	out, err := generate()
	require.NoError(t, err)

	body := string(out)
	require.Contains(t, body, "Generated by cmd/gen-api-types. Do not edit.")

	// Every type on the exported list appears, and so does everything they
	// reference — which is the whole point of following them automatically.
	for _, want := range []string{
		"export interface App {", "export interface Revision {",
		"export interface Deployment {", "export interface Detection {",
		"export interface GrantRow {", "export interface User {",
		"export interface Proposal {", "export interface Candidate {",
		"export interface Question {", "export interface AppSpec {",
		"export interface Error {",
		"export interface Workload {", "export interface Slot {",
	} {
		require.Contains(t, body, want)
	}

	// Nothing is declared twice, however many types reference it.
	require.Equal(t, 1, strings.Count(body, "export interface AppSpec {"))
}

func TestScalarsMapToTheirTypeScriptEquivalents(t *testing.T) {
	require.Equal(t, "string", tsTypeOf(t, ""))
	require.Equal(t, "boolean", tsTypeOf(t, false))

	for _, n := range []any{
		int(0), int8(0), int16(0), int32(0), int64(0),
		uint(0), uint16(0), uint32(0), uint64(0),
		float32(0), float64(0),
	} {
		require.Equal(t, "number", tsTypeOf(t, n), "%T", n)
	}
}

// Time is RFC 3339 on the wire (design 00 §3.5), so it is a string here and the
// console parses it deliberately rather than assuming a Date.
func TestTimeIsAStringRatherThanADate(t *testing.T) {
	require.Equal(t, "string", tsTypeOf(t, time.Time{}))
	require.Equal(t, "string", tsTypeOf(t, &time.Time{}))

	type hasTime struct {
		CreatedAt time.Time  `json:"created_at"`
		DeletedAt *time.Time `json:"deleted_at,omitempty"`
	}
	out := render(t, hasTime{})
	require.Contains(t, out, "created_at: string;")
	require.Contains(t, out, "deleted_at?: string;")
	require.NotContains(t, out, "interface Time", "time.Time is never expanded as a struct")
}

// A nil slice marshals as null, not [] — so the console is made to handle it.
func TestASliceIsNullableBecauseANilSliceMarshalsAsNull(t *testing.T) {
	require.Equal(t, "(string[] | null)", tsTypeOf(t, []string(nil)))
	require.Equal(t, "(number[] | null)", tsTypeOf(t, []int(nil)))
	require.Equal(t, "((string[] | null)[] | null)", tsTypeOf(t, [][]string(nil)))
	require.Equal(t, "(string[] | null)", tsTypeOf(t, [3]string{}))
}

func TestAMapIsANullableRecord(t *testing.T) {
	require.Equal(t, "(Record<string, string> | null)", tsTypeOf(t, map[string]string(nil)))
	require.Equal(t, "(Record<string, number> | null)", tsTypeOf(t, map[string]int(nil)))
}

// []byte is base64 in JSON and json.RawMessage is arbitrary JSON. Both are
// opaque to the console, and `unknown` forces it to say so.
func TestOpaqueBytesAndInterfacesBecomeUnknown(t *testing.T) {
	require.Equal(t, "unknown", tsTypeOf(t, []byte(nil))) //nolint:testifylint
	require.Equal(t, "unknown", tsTypeOf(t, json.RawMessage(nil)))

	type hasAny struct {
		Detail any `json:"detail"`
	}
	require.Contains(t, render(t, hasAny{}), "detail: unknown;")
}

// A pointer or an omitempty field may be absent from the JSON, and the console
// must be made to handle that rather than trusting it.
func TestAFieldThatCanBeAbsentIsOptional(t *testing.T) {
	type shapes struct {
		Always   string  `json:"always"`
		Omitted  string  `json:"omitted,omitempty"`
		Pointer  *string `json:"pointer"`
		Both     *int    `json:"both,omitempty"`
		Untagged string
	}

	out := render(t, shapes{})
	require.Contains(t, out, "always: string;")
	require.Contains(t, out, "omitted?: string;")
	require.Contains(t, out, "pointer?: string;")
	require.Contains(t, out, "both?: number;")
	require.Contains(t, out, "Untagged: string;", "an untagged field keeps its Go name")
}

func TestUnexportedAndSkippedFieldsAreNotEmitted(t *testing.T) {
	type shapes struct {
		Kept    string `json:"kept"`
		Skipped string `json:"-"`
		hidden  string //nolint:unused // present so the generator has one to skip
	}

	out := render(t, shapes{})
	require.Contains(t, out, "kept: string;")
	require.NotContains(t, out, "Skipped")
	require.NotContains(t, out, "hidden")
}

// Embedded structs are flattened, because that is what encoding/json does and
// the console has to match the wire rather than the Go declaration.
func TestAnEmbeddedStructIsFlattenedTheWayEncodingJSONFlattensIt(t *testing.T) {
	type Inner struct {
		Shared string `json:"shared"`
	}
	// Embedded with no name in the tag, which is the shape encoding/json
	// promotes into the outer object.
	type outer struct {
		Inner
		Own string `json:"own"`
	}

	out := render(t, outer{})
	require.Contains(t, out, "shared: string;")
	require.Contains(t, out, "own: string;")
	require.NotContains(t, out, "Inner: ", "the embedded struct is not a field of its own")
}

// A named embedded field is a field, not a flattening — same as encoding/json.
func TestANamedEmbeddedStructStaysNested(t *testing.T) {
	type Inner struct {
		Shared string `json:"shared"`
	}
	type outer struct {
		Inner `json:"inner"`
	}

	out := render(t, outer{})
	require.Contains(t, out, "inner: Inner;")
	require.Contains(t, out, "export interface Inner {")
}

// Anything an exported type references is followed automatically, which is what
// makes the explicit list safe: it names entry points, not the closure.
func TestReferencedStructsAreFollowedAndDeclaredOnce(t *testing.T) {
	type Leaf struct {
		Name string `json:"name"`
	}
	type Branch struct {
		One  Leaf   `json:"one"`
		Two  *Leaf  `json:"two"`
		Many []Leaf `json:"many"`
	}

	out := render(t, Branch{})
	require.Equal(t, 1, strings.Count(out, "export interface Leaf {"))
	require.Contains(t, out, "one: Leaf;")
	require.Contains(t, out, "two?: Leaf;")
	require.Contains(t, out, "many: (Leaf[] | null);")
}

// A type with no TypeScript equivalent fails the generator rather than emitting
// something the console would trust.
func TestATypeWithNoEquivalentIsAnErrorNamingTheField(t *testing.T) {
	type broken struct {
		Fn func() `json:"fn"`
	}

	g := &generator{done: map[reflect.Type]bool{}}
	_, err := g.fieldsOf(reflect.TypeOf(broken{}))
	require.ErrorContains(t, err, "no TypeScript equivalent")
	require.ErrorContains(t, err, "broken.Fn", "the message names the field that could not be rendered")
}

func TestDerefUnwrapsEveryLevelOfPointer(t *testing.T) {
	s := ""
	p := &s
	pp := &p

	require.Equal(t, reflect.TypeOf(""), deref(reflect.TypeOf(pp)))
	require.Equal(t, reflect.TypeOf(""), deref(reflect.TypeOf("")))
}

func TestEnqueueIgnoresWhatIsNotAStructAndWhatIsAlreadyDone(t *testing.T) {
	g := &generator{done: map[reflect.Type]bool{}}

	g.enqueue(reflect.TypeOf(""))
	g.enqueue(reflect.TypeOf(0))
	g.enqueue(reflect.TypeOf(time.Time{}))
	require.Empty(t, g.queue)

	type once struct {
		Name string `json:"name"`
	}
	g.enqueue(reflect.TypeOf(once{}))
	g.enqueue(reflect.TypeOf(once{}))
	require.Len(t, g.queue, 1, "a type queued twice is written once")
}

// Two exported types of one name would become two TypeScript interfaces of
// one name, which TypeScript merges silently. policy.Document and
// reference.Document were merged that way until the generator refused it.
func TestTwoTypesOfOneNameAreRefusedRatherThanMerged(t *testing.T) {
	_, err := generate()
	require.NoError(t, err, "the exported list has no collisions left")

	type Document struct{ A string }
	g := &generator{done: map[reflect.Type]bool{}}
	require.NoError(t, g.writeInterface(reflect.TypeOf(policy.Document{})))
	require.NoError(t, g.writeInterface(reflect.TypeOf(reference.Document{})))
	require.ErrorContains(t, g.writeInterface(reflect.TypeOf(Document{})), "both called Document")
	require.Contains(t, g.buf.String(), "export interface PolicyDocument {")
}
