package buildkit

import (
	"archive/tar"
	"bytes"
	"context"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/netip"
	"os"
	"path"
	"sort"
	"strings"
	"sync"

	cerrdefs "github.com/containerd/errdefs"
	"github.com/moby/moby/api/types/container"
	"github.com/moby/moby/api/types/mount"
	"github.com/moby/moby/api/types/network"
	"github.com/moby/moby/client"

	"github.com/trypando/pando/internal/errs"
)

// Pando starts its own BuildKit (R-111: "Pando starts it, hands it source,
// receives an image"), on the Docker daemon it runs apps on, unless it is
// told the address of one somebody else runs (issue #130).
//
// So that the install is one Compose file. BuildKit runs rootless, which needs
// user namespaces and mounts that Docker's default seccomp profile refuses,
// and the narrower profile it runs under instead has to reach Docker somehow:
// Compose reads a seccomp profile only from a file beside the Compose file,
// which made every install and upgrade download two files. The Docker API
// takes the profile itself, so Pando, which holds the API, passes the one
// compiled into it.
//
// Never a runtime socket, here or anywhere a build can see (R-112): the
// container gets its cache volume and a network shared with Pando, nothing of
// the host's.

// managedImage is the BuildKit Pando starts, pinned by digest: the bytes this
// version of Pando was built and tested against. v0.33.1, the line Pando's own
// BuildKit client is on. Dependabot does not read Go constants; bump it with
// the client in go.mod.
const managedImage = "moby/buildkit:v0.33.1-rootless@sha256:f8a833b2de9d68e27f0815e4a737abdfaf8a2e4c615650557df11025101557b4"

// managedArgs: listen where Pando can reach it, and run each step in
// BuildKit's own process namespace (--oci-worker-no-process-sandbox), since a
// rootless container cannot make another. A step can then signal, and may be
// able to ptrace, another step's processes — not the host's: BuildKit's own
// container is the boundary, and it holds only builds.
var managedArgs = []string{"--addr", "tcp://0.0.0.0:1234", "--oci-worker-no-process-sandbox"}

const (
	managedName    = "pando-buildkit"
	managedNetwork = "pando-build"
	managedVolume  = "pando-buildkit-cache"
	managedPort    = "1234"

	// labelManagedBuild marks the container and what it uses, with a digest
	// of everything it was created from, so a Pando with a different image or
	// profile replaces it rather than using a stale one. Not io.pando.managed,
	// which the runtime's cleanup reads as an app's: this is Pando's own.
	labelManagedBuild = "io.pando.buildkit"
)

// seccompProfile is Docker's default profile plus what rootless BuildKit
// needs, generated by scripts/buildkit-seccomp.py and guarded by
// TestR111_TheBuildKitSeccompProfileAddsOnlyWhatRootlessNeeds.
//
//go:embed seccomp.json
var seccompProfile []byte

// compactProfile is the profile as one line, the form the API takes inside a
// security option.
var compactProfile = sync.OnceValue(func() string {
	var b bytes.Buffer
	if err := json.Compact(&b, seccompProfile); err != nil {
		panic("buildkit: the embedded seccomp profile is not JSON: " + err.Error())
	}
	return b.String()
})

// digest is what the running container must have been created from: the
// image, its arguments, the profile, and the files it is given.
func (m *managed) digest() string {
	h := sha256.New()
	h.Write([]byte(managedImage))
	h.Write([]byte(strings.Join(managedArgs, " ")))
	h.Write([]byte(compactProfile()))
	names := make([]string, 0, len(m.files))
	for name := range m.files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		h.Write([]byte(name))
		h.Write(m.files[name])
	}
	h.Write([]byte(strings.Join(m.networks, ",")))
	return hex.EncodeToString(h.Sum(nil))[:16]
}

// registryFiles are what a BuildKit needs to push to, and pull from, a
// registry signed by a CA of the installation's own (docker-compose.registry.yml):
// its configuration naming the CA, and the CA. Paths under the BuildKit user's
// home.
func registryFiles(host string, ca []byte) map[string][]byte {
	if host == "" || len(ca) == 0 {
		return nil
	}
	const caPath = ".config/buildkit/registry-ca.crt"
	return map[string][]byte{
		".config/buildkit/buildkitd.toml": fmt.Appendf(nil, "[registry.%q]\n  ca = [%q]\n", host, "/home/user/"+caPath),
		caPath:                            ca,
	}
}

// dockerAPI is the part of the Docker client the managed BuildKit uses.
type dockerAPI interface {
	ContainerInspect(ctx context.Context, id string, opts client.ContainerInspectOptions) (client.ContainerInspectResult, error)
	ContainerCreate(ctx context.Context, opts client.ContainerCreateOptions) (client.ContainerCreateResult, error)
	ContainerStart(ctx context.Context, id string, opts client.ContainerStartOptions) (client.ContainerStartResult, error)
	ContainerRemove(ctx context.Context, id string, opts client.ContainerRemoveOptions) (client.ContainerRemoveResult, error)
	ImageInspect(ctx context.Context, ref string, opts ...client.ImageInspectOption) (client.ImageInspectResult, error)
	ImagePull(ctx context.Context, ref string, opts client.ImagePullOptions) (client.ImagePullResponse, error)
	NetworkList(ctx context.Context, opts client.NetworkListOptions) (client.NetworkListResult, error)
	NetworkCreate(ctx context.Context, name string, opts client.NetworkCreateOptions) (client.NetworkCreateResult, error)
	NetworkConnect(ctx context.Context, id string, opts client.NetworkConnectOptions) (client.NetworkConnectResult, error)
	VolumeCreate(ctx context.Context, opts client.VolumeCreateOptions) (client.VolumeCreateResult, error)
	CopyToContainer(ctx context.Context, id string, opts client.CopyToContainerOptions) (client.CopyToContainerResult, error)
}

// managed is a BuildKit Pando runs.
//
// Named after the Compose project Pando's own container belongs to, the way
// Compose names its containers — pando-buildkit for the shipped file's — so
// two installations on one Docker daemon, such as an operator's and a
// throwaway one the deploy QA run brings up beside it, each run their own and
// never remove the other's. Outside Compose, pando.
type managed struct {
	cli                         dockerAPI
	name, network, volume, port string

	// named says the names were chosen by the caller (a test) and are not to
	// be taken from the Compose project.
	named bool

	// self is Pando's own container, which joins the network; empty asks the
	// hostname, which is the container ID when Pando is in one.
	self string

	// files are written under the BuildKit user's home before it starts:
	// registryFiles, when the installation runs a registry of its own.
	files map[string][]byte

	// networks are joined besides its own, by name: the one the
	// installation's registry is on (docker-compose.registry.yml), so a push
	// reaches it. Only those named — never Pando's own networks, where its
	// database is (R-113).
	networks []string

	mu sync.Mutex
}

func newManaged(cli dockerAPI) *managed {
	return &managed{cli: cli, name: managedName, network: managedNetwork, volume: managedVolume, port: managedPort}
}

// labelComposeProject is the label Compose puts on every container it starts.
const labelComposeProject = "com.docker.compose.project"

// nameAfterProject takes the names from the Compose project of Pando's own
// container, when it is in one.
func (m *managed) nameAfterProject(ctx context.Context) {
	if m.named {
		return
	}
	self := m.self
	if self == "" {
		host, err := os.Hostname()
		if err != nil {
			return
		}
		self = host
	}
	got, err := m.cli.ContainerInspect(ctx, self, client.ContainerInspectOptions{})
	if err != nil || got.Container.Config == nil {
		return
	}
	if project := got.Container.Config.Labels[labelComposeProject]; project != "" {
		m.name, m.network, m.volume = project+"-buildkit", project+"-build", project+"-buildkit-cache"
	}
}

// address is where Pando reaches the BuildKit it runs: by name on the network
// they share, or on the host's loopback when Pando is not in a container — a
// developer running the binary.
func (m *managed) address(inContainer bool) string {
	if inContainer {
		return "tcp://" + m.name + ":" + managedPort
	}
	return "tcp://127.0.0.1:" + m.port
}

// ensure makes the BuildKit container exist, match this Pando, run, and share
// a network with Pando, and returns its address. Idempotent, and safe for
// several replicas at once: the name is fixed, and a create that loses the
// race finds the winner's container.
func (m *managed) ensure(ctx context.Context) (string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.nameAfterProject(ctx)
	networkID, err := m.ensureNetwork(ctx)
	if err != nil {
		return "", err
	}
	inContainer, err := m.joinNetwork(ctx, networkID)
	if err != nil {
		return "", err
	}
	addr := m.address(inContainer)

	want := m.digest()
	got, err := m.cli.ContainerInspect(ctx, m.name, client.ContainerInspectOptions{})
	switch {
	case err == nil && got.Container.Config != nil && got.Container.Config.Labels[labelManagedBuild] == want:
		if got.Container.State != nil && got.Container.State.Running {
			return addr, nil
		}
		return addr, m.start(ctx, got.Container.ID)
	case err == nil:
		// Made by a Pando with another image or profile: replaced, so this
		// one builds with what it was built against.
		if _, err := m.cli.ContainerRemove(ctx, got.Container.ID, client.ContainerRemoveOptions{Force: true}); err != nil && !cerrdefs.IsNotFound(err) {
			return "", errs.Wrap(errs.AdapterFailed, "Could not replace Pando's build service with this version's.", err)
		}
	case !cerrdefs.IsNotFound(err):
		return "", errs.Wrap(errs.AdapterUnavailable, "Could not look for Pando's build service.", err)
	}

	if err := m.ensureImage(ctx); err != nil {
		return "", err
	}
	if _, err := m.cli.VolumeCreate(ctx, client.VolumeCreateOptions{
		Name: m.volume, Labels: map[string]string{labelManagedBuild: "cache"},
	}); err != nil {
		return "", errs.Wrap(errs.AdapterFailed, "Could not create the build service's cache.", err)
	}

	hostCfg := &container.HostConfig{
		Mounts: []mount.Mount{{Type: mount.TypeVolume, Source: m.volume, Target: "/home/user/.local/share/buildkit"}},
		// Docker's default AppArmor profile denies mount, which builds cannot
		// do without, and a narrower one has to be loaded into the host's
		// kernel by root. The seccomp profile is the narrowed one.
		SecurityOpt:   []string{"seccomp=" + compactProfile(), "apparmor=unconfined"},
		RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyUnlessStopped},
	}
	if !inContainer {
		// Loopback only: reachable from a host-run Pando, and from nothing
		// off the machine.
		hostCfg.PortBindings = network.PortMap{
			network.MustParsePort(managedPort + "/tcp"): {{HostIP: netip.MustParseAddr("127.0.0.1"), HostPort: m.port}},
		}
	}
	created, err := m.cli.ContainerCreate(ctx, client.ContainerCreateOptions{
		Name: m.name,
		Config: &container.Config{
			Image:  managedImage,
			Cmd:    managedArgs,
			Labels: map[string]string{labelManagedBuild: want},
			ExposedPorts: network.PortSet{
				network.MustParsePort(managedPort + "/tcp"): {},
			},
		},
		HostConfig: hostCfg,
		NetworkingConfig: &network.NetworkingConfig{
			EndpointsConfig: map[string]*network.EndpointSettings{m.network: {NetworkID: networkID}},
		},
	})
	if cerrdefs.IsConflict(err) {
		// Another replica made it between the inspect and the create.
		got, err := m.cli.ContainerInspect(ctx, m.name, client.ContainerInspectOptions{})
		if err != nil {
			return "", errs.Wrap(errs.AdapterUnavailable, "Could not look for Pando's build service.", err)
		}
		return addr, m.start(ctx, got.Container.ID)
	}
	if err != nil {
		return "", errs.Wrap(errs.AdapterFailed, "Could not create Pando's build service.", err)
	}
	if err := m.copyFiles(ctx, created.ID); err != nil {
		return "", err
	}
	for _, n := range m.networks {
		if _, err := m.cli.NetworkConnect(ctx, n, client.NetworkConnectOptions{Container: created.ID}); err != nil {
			return "", errs.Wrap(errs.AdapterFailed, "Could not connect the build service to the network "+n+".", err).
				WithRemedy("PANDO_BUILDKIT_NETWORKS names it; check that it exists with docker network ls.")
		}
	}
	return addr, m.start(ctx, created.ID)
}

// copyFiles writes m.files into the container before it first starts, owned by
// the rootless BuildKit's user (1000), which reads its configuration from its
// home.
func (m *managed) copyFiles(ctx context.Context, id string) error {
	if len(m.files) == 0 {
		return nil
	}
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	names := make([]string, 0, len(m.files))
	for name := range m.files {
		names = append(names, name)
	}
	sort.Strings(names)
	dirs := map[string]bool{}
	for _, name := range names {
		for d := path.Dir(name); d != "." && !dirs[d]; d = path.Dir(d) {
			dirs[d] = true
		}
	}
	dirList := make([]string, 0, len(dirs))
	for d := range dirs {
		dirList = append(dirList, d)
	}
	sort.Strings(dirList) // parents sort before their children
	for _, d := range dirList {
		if err := tw.WriteHeader(&tar.Header{Typeflag: tar.TypeDir, Name: d + "/", Mode: 0o755, Uid: 1000, Gid: 1000}); err != nil {
			return errs.Wrap(errs.Internal, "Could not prepare the build service's configuration.", err)
		}
	}
	for _, name := range names {
		body := m.files[name]
		if err := tw.WriteHeader(&tar.Header{Name: name, Mode: 0o644, Size: int64(len(body)), Uid: 1000, Gid: 1000}); err != nil {
			return errs.Wrap(errs.Internal, "Could not prepare the build service's configuration.", err)
		}
		if _, err := tw.Write(body); err != nil {
			return errs.Wrap(errs.Internal, "Could not prepare the build service's configuration.", err)
		}
	}
	if err := tw.Close(); err != nil {
		return errs.Wrap(errs.Internal, "Could not prepare the build service's configuration.", err)
	}
	if _, err := m.cli.CopyToContainer(ctx, id, client.CopyToContainerOptions{DestinationPath: "/home/user", Content: &buf}); err != nil {
		return errs.Wrap(errs.AdapterFailed, "Could not give the build service its registry configuration.", err)
	}
	return nil
}

func (m *managed) start(ctx context.Context, id string) error {
	if _, err := m.cli.ContainerStart(ctx, id, client.ContainerStartOptions{}); err != nil {
		return errs.Wrap(errs.AdapterFailed, "Could not start Pando's build service.", err).
			WithRemedy("Run docker logs " + m.name + " on the host for BuildKit's own account of why. " +
				"On a host that confines unprivileged user namespaces, such as Ubuntu 24.04, rootless BuildKit cannot start " +
				"until kernel.apparmor_restrict_unprivileged_userns is 0.")
	}
	return nil
}

func (m *managed) ensureImage(ctx context.Context) error {
	if _, err := m.cli.ImageInspect(ctx, managedImage); err == nil {
		return nil
	}
	rc, err := m.cli.ImagePull(ctx, managedImage, client.ImagePullOptions{})
	if err != nil {
		return errs.Wrap(errs.AdapterFailed, "Could not fetch the build service's image "+managedImage+".", err).
			WithRemedy("The host needs to reach Docker Hub once, or the image can be pulled by hand with docker pull.")
	}
	defer func() { _ = rc.Close() }()
	// Drained: a pull that is not read to the end does not finish.
	_, _ = io.Copy(io.Discard, rc)
	return nil
}

func (m *managed) ensureNetwork(ctx context.Context) (string, error) {
	existing, err := m.cli.NetworkList(ctx, client.NetworkListOptions{
		Filters: make(client.Filters).Add("name", m.network),
	})
	if err != nil {
		return "", errs.Wrap(errs.AdapterUnavailable, "Could not list Docker networks.", err)
	}
	for _, n := range existing.Items {
		if n.Name == m.network {
			return n.ID, nil
		}
	}
	created, err := m.cli.NetworkCreate(ctx, m.network, client.NetworkCreateOptions{
		Driver: "bridge", Labels: map[string]string{labelManagedBuild: "network"},
	})
	if cerrdefs.IsConflict(err) {
		return m.ensureNetwork(ctx)
	}
	if err != nil {
		return "", errs.Wrap(errs.AdapterFailed, "Could not set up the network Pando shares with its build service.", err)
	}
	return created.ID, nil
}

// joinNetwork connects Pando's own container to the build network, and says
// whether Pando is in a container at all.
func (m *managed) joinNetwork(ctx context.Context, networkID string) (bool, error) {
	self := m.self
	if self == "" {
		host, err := os.Hostname()
		if err != nil {
			//nolint:nilerr // No hostname, no container to join: Pando is on the host, which address() handles.
			return false, nil
		}
		self = host
	}
	_, err := m.cli.NetworkConnect(ctx, networkID, client.NetworkConnectOptions{Container: self})
	switch {
	case err == nil, strings.Contains(err.Error(), "already exists"):
		return true, nil
	case cerrdefs.IsNotFound(err):
		// No container by that name: Pando is running on the host.
		return false, nil
	default:
		return false, errs.Wrap(errs.AdapterFailed,
			"Could not connect Pando to the network it shares with its build service.", err)
	}
}
