#!/usr/bin/env python3
"""Write buildkit-seccomp.json: Docker's default seccomp profile, plus the system
calls rootless BuildKit needs to run builds, and nothing else (issue #130).

usage: python3 scripts/buildkit-seccomp.py > buildkit-seccomp.json

Rootless BuildKit puts each build step in a user namespace of its own, so it has
to create namespaces and mount inside them. Docker's default profile allows
those calls only to a container holding CAP_SYS_ADMIN, which BuildKit's container
does not have and must not be given. Without a profile, the only alternative is
seccomp=unconfined, which also hands builds bpf, perf_event_open, kernel module
loading, kexec, reboot and the clock.

Each call below was found by running a build under the default profile and
adding the call it failed on, one at a time, until builds passed:

  clone, clone3, unshare, setns       rootlesskit's child, and each step's runc
  mount and the new mount API,        the step's root filesystem and the mounts
  umount2, pivot_root                 BuildKit gives it (cache, tmpfs, secrets)
  keyctl                              runc gives each step its own session keyring
  sethostname, setdomainname          each step's hostname, in its own UTS namespace

The base is pinned to a commit, not a tag: moby/profiles main blocked AF_AX25
sockets after the last tag, and the stricter one is the one tested.
"""
import json
import sys
import urllib.request

BASE = ("https://raw.githubusercontent.com/moby/profiles/"
        "6fe7deb1b9fb7c0397a4593480d7d22b9ee8caef/seccomp/default.json")

ROOTLESS_BUILDKIT = [
    "clone", "clone3", "unshare", "setns",
    "mount", "umount2", "pivot_root",
    "mount_setattr", "move_mount", "open_tree", "fsopen", "fsconfig", "fsmount", "fspick",
    "keyctl",
    "sethostname", "setdomainname",
]


def main():
    with urllib.request.urlopen(BASE) as resp:
        profile = json.load(resp)
    # Strip the added calls from every other rule, so that neither an ERRNO rule
    # nor an argument-filtered allow (clone without namespace flags) shadows the
    # unconditional allow below.
    rules = []
    for rule in profile["syscalls"]:
        rest = [n for n in rule["names"] if n not in ROOTLESS_BUILDKIT]
        if rest:
            rule["names"] = rest
            rules.append(rule)
    rules.append({
        "names": sorted(ROOTLESS_BUILDKIT),
        "action": "SCMP_ACT_ALLOW",
        "comment": "Rootless BuildKit: user namespaces, mounts inside them, and runc's per-step "
                   "keyring and hostname. Generated by scripts/buildkit-seccomp.py (issue #130).",
    })
    profile["syscalls"] = rules
    json.dump(profile, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
